version: "3.7"

services:
  player:
    build:
      context: ./player
      dockerfile: Dockerfile
    #image: bekirkocabas/player-server:latest #for that I must build earlier this image 
    container_name: player
    restart: always
    ports:
      - "5000:5000"
    networks:
      - tasknetwork
    healthcheck:
      test: ["CMD", "curl", "-f", "http://player/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - master
      
  master:
    build:
      context: ./master
      dockerfile: Dockerfile
    #image: bekirkocabas/master-server:latest #for that I must build earlier this image
    container_name: master
    restart: always
    ports:
      - "5001:5001"
    networks:
      - tasknetwork
    healthcheck:
      test: ["CMD", "curl", "-f", "http://master/health"]
      interval: 30s
      timeout: 10s
      retries: 3
  
networks:
  tasknetwork:
    driver: bridge
